List<Map<String, dynamic>> chatsData = [
  {
    "thumb": "assets/images/profiles/p1.jpg",
    "user": "John Doe",
    "message": "What is it all about ?",
    "date": "12:30",
    "count": 4,
    "mute": true,
    "pin": false,
  },
  {
    "thumb": "assets/images/profiles/p2.jpg",
    "user": "Jane Doe",
    "message": "I like nature",
    "date": "09:30",
    "count": 1,
    "mute": false,
    "pin": false,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "message": "Pottery is my passion",
    "date": "01:30",
    "count": 2,
    "mute": false,
    "pin": true,
  },
];

List<Map<String, dynamic>> statusData = [
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "last": "01 hour ago",
    "count": 2,
  },
  {
    "thumb": "assets/images/profiles/p1.jpg",
    "user": "John Doe",
    "last": "12 minutes ago",
    "count": 4,
  },
  {
    "thumb": "assets/images/profiles/p2.jpg",
    "user": "Jane Doe",
    "last": "09 minutes ago",
    "count": 1,
  },
];

List<Map<String, dynamic>> callsData = [
  {
    "thumb": "assets/images/profiles/p3.jpg",
    "user": "Mimi Black",
    "last": "Today, 14:30",
    "count": 2,
    "direction": "in",
    "missed": true,
  },
  {
    "thumb": "assets/images/profiles/p1.jpg",
    "user": "John Doe",
    "last": "Today, 08:30",
    "count": 4,
    "direction": "in",
    "missed": false,
  },
  {
    "thumb": "assets/images/profiles/p2.jpg",
    "user": "Jane Doe",
    "last": "Yesterday, 21:10",
    "count": 1,
    "direction": "out",
    "missed": true,
  },
];
